### ISSUE TITLE
MapSpread callable(mixed) expected

### ISSUE THREAD

**Issue by billypoke** [nunomaduro/larastan#1109]
- Larastan Version: 2.0.0
- `--level` used: 5

### Description

Trying to use the mapSpread collection method with laravel 9 beta 5, I get the following error:

`Parameter #1 $callback of method Illuminate\Support\Collection<int,array<int, string>>::mapSpread() expects callable(mixed): string, Closure(string, string): string given.`

I am able to solve this by converting the code to use the `...` operator, but this looks way worse. What am I missing?

### Laravel code where the issue was found

Gives Error
```php
collect(['a', 'b', 'c'])
    ->crossJoin(['x', 'y'])
    ->mapSpread(fn(string $foo, string $bar) => $foo && $bar ? "$foo is $bar" : '')
```

No Error
```php
collect(['a', 'b', 'c'])
    ->crossJoin(['x', 'y'])
    ->mapSpread(fn(...$args) => $args['foo'] && $args['bar'] ? "{$args['foo']} is {$args['bar']}" : '')
```

**Comment by canvural** [comment]
Hi,

The problem is that the number of arguments in `mapSpread` depends on the collection it's called. And the PHPDoc `callable(mixed)` expects just one argument.

Probably it should be defined as variadic like `callable(mixed ...$args)`

Also as of Larastan 2, all the collection related stubs are moved to Laravel core. So please open an issue there, or better yet open a PR with the fix I suggested. Thanks.

**Comment by billypoke** [comment]
No worries. That makes sense, thanks for confirming

**Comment by billypoke** [comment]
Looks like there is an open issue on phpstan already https://github.com/phpstan/phpstan/issues/5060
