### ISSUE TITLE
afterCreating method does not accept Closure(Model)

### ISSUE THREAD

**Issue by Batisska** [nunomaduro/larastan#1131]
- Larastan Version: 2.0.0
- `--level` used: 8 

### Description

Every time I call afterMaking or afterCreating phpstan crashes with an error.

### Laravel code where the issue was found

```php

    /**
     * @return TaskFactory
     */
    public function configure(): TaskFactory
    {
        return $this->afterCreating(function (Task $task) {
            $task->assigned()->attach(User::factory()->count(5)->create());
            $task->files()->attach(File::factory()->count(5)->create());
        });
    }
```

```
Parameter #1 $callback of method Illuminate\Database\Eloquent\Factories\Factory<Illuminate\Database\Eloquent\Model>::afterCreating() expects 
    Closure(Illuminate\Database\Eloquent\Model): mixed,
    Closure(App\Data\Models\Task): void given.    
```

**Comment by szepeviktor** [comment]
Hello Сергей! 👋 

Thank you for your report.
I see two possible solutions.
Does `Task` extend `Model`?
What if you return something?

**Comment by szepeviktor** [comment]
Thank you!
It is a bug.

**Comment by szepeviktor** [comment]
No. We need generics!

```php
/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Data\Models\Task>
 */
class TaskFactory extends Factory
{
```

But I cannot get it working.

**Comment by Batisska** [comment]
> No. We need [generics](https://github.com/laravel/framework/blob/4c7cd8c4e95d161c0c6ada6efa0a5af4d0d487c9/src/Illuminate/Database/Eloquent/Factories/Factory.php#L591)!
> 
> ```
> /**
>  * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Data\Models\Task>
>  */
> class TaskFactory extends Factory
> {
> ```
> 
> But I cannot get it working.

What information can I provide you? To understand where the bug crept in? Thank you.

**Comment by szepeviktor** [comment]
@canvural Can you help us? We are a bit lost.

**Comment by canvural** [comment]
Hello,

The [types](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Factories/Factory.php#L591) are coming from Laravel itself. So I suggest opening an issue there.

A solution would be to change the type [here](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Factories/Factory.php#L591) to just `\Closure(TModel): mixed` Since `TModel` is bound to EloquentModel anyway, there is no need of an union type. I think that would resolve the issue.

Also instead of an issue you can directly create a PR there. Feel free to link this issue or this comment.

Thanks.

**Comment by mdpoulter** [comment]
@canvural It looks like Laravel won't be making that change in the near future, as the delay is IDE support (https://github.com/laravel/framework/pull/41286). Is this something which Larastan can support in the meantime?

**Comment by canvural** [comment]
@mdpoulter Yeah, I guess we can do that. It should be added to [this](https://github.com/nunomaduro/larastan/blob/master/stubs/Factory.stub) stub file.
