### ISSUE TITLE
abort_if not treated like if statements by type checker

### ISSUE THREAD

**Issue by keryja** [nunomaduro/larastan#116]
- Larastan Version: 0.2.4
- `--level` used: max

### Description:
Currently `abort_if` does not seem to get treated similarly to if, anything designated as nullable is still considered nullable after `abort_if`

This results in an error when querying relations on the object:
```
Cannot call method theRelation() on mixed.
```

### Workaround/example:
Current workaround for this is to use an if statement with a regular `abort`:

```php
// Doesn't pass checks
$foo = ModelName::where(['foo' => 'bar'])->first();
abort_if(!$foo, 404);

print_r($foo->theRelation());

// Passes checks
$foo = ModelName::where(['foo' => 'bar'])->first();
if (!$foo) {
  abort(404);
}

print_r($foo->theRelation());
```

**Comment by ondrejmirtes** [comment]
Well, first, this is a very weird error message that shouldn't happen: `Cannot call method theRelation() on mixed.`. I'm not sure how that can happen, because MixedType should pass this.

But to the original issue, Larastan should contain these two things:

* `abort_if` should have a very similar type-specifying extension to `assert` that is in the core
* `abort` should be an `earlyTerminatingFunctionCall` which is not yet possible to configure in PHPStan, just for methods. I'll welcome a PR to phpstan/phpstan that allows this.

**Comment by keryja** [comment]
On `--level=max` calling methods on mixed do trigger errors so that's probably why it occurs.

I've whipped up a repository that reproduces the error, before reading your reply fully, anyway if it's ever needed [keryja/larastan-error-examples#reproduce-abort-if](https://github.com/keryja/larastan-error-examples/commit/ec155630fd72951eb3bde59951ff4cb29940967e).

```
 22/22 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ --------------------------------------------
  Line   app/Http/Controllers/TheController.php
 ------ --------------------------------------------
  16     Cannot call method theRelation() on mixed.
 ------ --------------------------------------------

 [ERROR] Found 1 error
```

**Comment by ondrejmirtes** [comment]
> On --level=max calling methods on mixed do trigger errors

They don't. The type there must be something else, not MixedType.

**Comment by nunomaduro** [comment]
@keryja This issue still exists on the latest version?
