### ISSUE TITLE
Model Factory::count() support

### ISSUE THREAD

**Issue by LastDragon-ru** [nunomaduro/larastan#1182]
- Larastan Version: 2.1.2

### Description

Factory support [`count()`](https://laravel.com/docs/9.x/database-testing#instantiating-models) method that allow create multiple instances. Unfortunately, it is not supported yet.

### Laravel code where the issue was found

```php
$collection = Model::factory()->count(10)->create()->map(); // Call to undefined method Model::map()
```

**Comment by canvural** [comment]
Hi,

The return type of your example is `Model|Illuminate\Database\Eloquent\Collection<int, Model>` It's because we cannot know if `create` returns a collection or the object. It's a hard task for static analysis. Users could also do `Model::factory(5)->create()`

What I suggest for you to do is help yourself with inline var.

```php
/** @var Collection<int, Model> $collection */
$collection = Model::factory()->count(10)->create();
```

And, I don't see a point of keeping this issue open, because I don't think we'll ever support this. But if you find a solution, you can send a PR.

Thank you.
