### ISSUE TITLE
Call to undefined error for macro method

### ISSUE THREAD

**Issue by rovansteen** [nunomaduro/larastan#1315]
- Larastan Version: 2.1.12
- `--level` used: 6
- Pull request with failing test: N/A

### Description
Since `2.1.12` it seems (some?) macro's are no longer being recognised by larastan. I am using [`momentum/modal`](https://github.com/lepikhinb/momentum-modal) that registers a macro `Inertia::dialog` which didn't report any errors prior to the latest version. But now it's giving the following error:
```
Call to an undefined static method Inertia\Inertia::dialog().
```

### Laravel code where the issue was found

```php
class CreateEventDialog extends Controller
{
    public function __invoke(): Modal
    {
        return Inertia::dialog('events/create')
            ->baseRoute('events');
    }
}
```

**Comment by szepeviktor** [comment]
Thank you for your report, Robert!

👋🏻

We will resolve this issue.
Could you downgrade Larastan and confirm that `dialog` is recognized?

**Comment by rovansteen** [comment]
@szepeviktor thanks for the quick response. Yes can confirm that there are no errors being reported on `2.1.11` for the same code.

**Comment by szepeviktor** [comment]
The latest release includes #1295
So we have to review that again.

**Comment by jnoordsij** [comment]
I found similar problems in my setup (see #1324). For this purpose, I made a MWE that might be useful: https://github.com/jnoordsij/laravel/tree/larastan-mwe.

**Comment by xwillq** [comment]
Hey @szepeviktor! I believe I've found the bug. Before this PR, `NunoMaduro\Larastan\Methods\Kernel` checked for macros and it also checks for facades. When it found a facade, it send underlying class back to the kernel pipeline, where macro was found.
But now `NunoMaduro\Larastan\Methods\MacroMethodsClassReflectionExtension` checks for macros and it doesn't know anything about facades.

So, to fix this bug, we could handle facades in `MacroMethodsClassReflectionExtension` or rollback the PR and fix that issue in some other way, so check for macros stays in `Kernel`.

IMO, second option is better because recursive search for class that actually will receive the method call can be quite useful, but I don't know the code base of Larastan, so I might be wrong.

**Comment by szepeviktor** [comment]
@canvural Please jump in after you returned from holiday.

**Comment by canvural** [comment]
@rovansteen @jnoordsij Can you try the latest `master` branch and see if it fixes your issues?

**Comment by jnoordsij** [comment]
> @rovansteen @jnoordsij Can you try the latest `master` branch and see if it fixes your issues?

My usecase and the MWE I listed above still seem to be failing on the latest version (`dev-master` commit ffbf0f56c1fcfc5cc8efb613f8782310a6c21813).

**Comment by canvural** [comment]
Fixed with https://github.com/nunomaduro/larastan/commit/4e53a5f6d5a6dd77117f4c49bbbf21534baa5ba4
