### ISSUE TITLE
`Model::find()` returns the wrong type when using generics

### ISSUE THREAD

**Issue by mwnciau** [nunomaduro/larastan#1546]
- Larastan Version: 2.3.0
- `--level` used: 9

### Description

When updating from Larastan 2.2.9 to 2.3.0, the following code starts throwing an error:

```
Function findModel() should return (T of Illuminate\Database\Eloquent\Model)|null
  but returns Illuminate\Database\Eloquent\Model|null.
```

### Laravel code where the issue was found

```php
use Illuminate\Database\Eloquent\Model;

/**
 * @template T of Model
 * @param class-string<T> $modelClassName
 * @return T|null
 */
function findModel(string $modelClassName, int $id): ?Model
{
    return $modelClassName::find($id);
}
```

### Comments

This issue looks similar to #1149, but only started occurring after an update after that issue was created so possibly unrelated.

The PHPStan version did not affect the error returned. It looks like the `$modelClassName::find()` method is inferred to always return the type `Model` instead of `T`.

**Comment by canvural** [comment]
Hi,

I think this error would only happen when you analyze this function alone. Because there is no type to infer for generic parameter `T` PHPStan uses the bounded type (`Model` in this case)

Does this error happen when you analyze for example `findModel(User::class, 1)` ? If not you can safely ignore this error.
