### ISSUE TITLE
Mismatch between stubs and actual type definitions in Laravel 10

### ISSUE THREAD

**Issue by aharisu** [nunomaduro/larastan#1547]
- Larastan Version: 2.4
- `--level` used: 6

### Description
The type of arguments that the "where" method of the \\Illuminate\\Database\\Eloquent\\Builder class receives has changed in Laravel 10.
Stub type definitions are out of date, resulting in type checking errors.

### Laravel code where the issue was found

```php
use App\Models\User;
use Illuminate\Support\Facades\DB;

function test(): void
{
    User::query()->where(DB::raw('name'), '=', 'foo');
}
```

### Laravel 9.x type definition
```php
    /**
     * Add a basic where clause to the query.
     *
     * @param  \Closure|string|array|\Illuminate\Database\Query\Expression  $column
     * @param  mixed  $operator
     * @param  mixed  $value
     * @param  string  $boolean
     * @return $this
     */
    public function where($column, $operator = null, $value = null, $boolean = 'and')
```

### Laravel 10 type definition
```php
    /**
     * Add a basic where clause to the query.
     *
     * @param  \Closure|string|array|\Illuminate\Contracts\Database\Query\Expression  $column
     * @param  mixed  $operator
     * @param  mixed  $value
     * @param  string  $boolean
     * @return $this
     */
    public function where($column, $operator = null, $value = null, $boolean = 'and')
```

**Comment by szepeviktor** [comment]
Hello!
`Contracts` seems like a bug.

**Comment by aharisu** [comment]
Thanks for comment.

I thought the type change was related to https://laravel.com/docs/10.x/upgrade#database-expressions.

**Comment by szepeviktor** [comment]
I may be wrong!

**Comment by canvural** [comment]
We'd need to add some logic to https://github.com/nunomaduro/larastan/blob/master/src/LarastanStubFilesExtension.php so we can include different stub files depending on Laravel version. Then we can have stubs for Laravel 10 where it has `\Illuminate\Contracts\Database\Query\Expression` type-hints.

**Comment by aharisu** [comment]
Hello,

I tried creating a function to switch stub files in Laravel versions. What do you think?

https://www.tehplayground.com/3aR0cQ666Rxb0ScS

In this sample, I specify the version in the filename as "filename.v10.stub". By writing v10, it will be used in Laravel version 10.0.0 or higher.
If it is lower than 10, the default file will be used.

**Comment by craigfrancis** [comment]
To create a PR to address the version differences, and hopefully add my own feature (to check [Raw methods don't contain Injection Vulnerabilities](https://github.com/laravel/framework/discussions/47257)).

Do you have a preference on how stub files should be stored in Larastan?

At the moment there is a `/stubs/` folder, and all `*.stub` files are loaded via [LarastanStubFilesExtension](https://github.com/nunomaduro/larastan/blob/master/src/LarastanStubFilesExtension.php).

We could use the file name, e.g. "EloquentBuilder.stub" for the older versions, then "EloquentBuilder.v10.stub" can replace it for v10+ (as suggested by @aharisu); or inverted so "EloquentBuilder.stub" is loaded by default, and "EloquentBuilder.v9.stub" would be used if the Laravel version matches or is less than.

Or, how about using folders? e.g. stub files in `/stubs/latest/main/` would be used by default, older versions can override these files by putting them in `/stubs/9.0.0/main/`, and then `/stubs/latest/feature/` for optional features (i.e. stub files in this folder would override those in `../main/`).

I suspect folders will be a bit faster (i.e. a single `version_compare()` for the version folders, rather than a RegEx and comparison on every file); and while minor, it would make archiving easier (i.e. when v9 is no longer supported, just delete that folder).

Also, do you have a preference on how to collect the installed version of Laravel?

1. Read from `composer.json`
2. Execute `php artisan --version`
3. Read from `/Illuminate/Foundation/Application.php`

**Comment by canvural** [comment]
I love the folder idea! That was what I was thinking too initially. 

And for the Laravel version we can use `LARAVEL_VERSION` constant. Since we boot up the framework it is available for us. And we already make use of it [here](https://github.com/nunomaduro/larastan/blob/73e5be5f5c732212ce6ca77ffd2753a136f36a23/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php#L47), and it works fine.

**Comment by aharisu** [comment]
I agree with the idea of using folders.

The reason I proposed separating them by file names is that I thought it would make it easier to see when stub files with different versions are listed together, as they would be grouped closely.

However, I also like the idea of separating them into folders because it seems more versatile.

**Comment by canvural** [comment]
Implemented in https://github.com/nunomaduro/larastan/pull/1710

@craigfrancis You can work on your feature now 😊

**Comment by craigfrancis** [comment]
> @craigfrancis You can work on your feature now 😊

Thanks @canvural, I really appreciate this, it's been on my todo list for weeks.

I have started [PR 1715](https://github.com/nunomaduro/larastan/pull/1715), but will probably need help (e.g. are you happy with the stubs being included in the way I've done it). I'll leave this ticket though, as this is going a bit off topic :-)
