### ISSUE TITLE
Call to protected static method in Storage facade

### ISSUE THREAD

**Issue by tranba** [nunomaduro/larastan#158]
- Larastan Version: 0.3.1
- `--level` used: 0

### Description:
I try to analyse my project and get error:
`Call to protected static method get() of class Illuminate\Filesystem\FilesystemManager`
### Laravel code where the issue was found:

```php
...
use Illuminate\Support\Facades\Storage;
...
$myFile = Storage::get($path); // <- at this line
```

**Comment by phroggyy** [comment]
It appears this would be an issue with phpstan not correctly parsing `@mixin`, but instead using `@see` for links. The `Storage` facade has `@see \Illuminate\Filesystem\FilesystemManager`, and that manager then has `@mixin \Illuminate\Contracts\Filesystem\Filesystem`, which it appears phpstan fails to interpret correctly (as `@mixin` is not officially a support docblock annotation). Using `@see` in the Laravel framework might be the proper fix here

**Comment by devinpearson** [comment]
Storage::drive()->get() and it clears the error.

**Comment by Daanra** [comment]
Since the Storage facade now has `get` and other methods defined using [PHPDoc annotations](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Facades/Storage.php#L30), this particular issue no longer exists. Since there is also a [similar issue](https://github.com/nunomaduro/larastan/issues/203) for Facades that use a manager pattern, I suppose this issue can be closed. What do you think @canvural ?

**Comment by canvural** [comment]
@Daanra  Yeah looks those annotations are in both 6.x and 7.x so we can close this issue :+1:
