### ISSUE TITLE
Shows unknown packages etc??

### ISSUE THREAD

**Issue by shirshak55** [nunomaduro/larastan#167]
Default level.

I follow modular pattern so don't have app folder. So as usual i used larastan like this

```
$ php artisan code:analyse  --paths='modules'
```

But it throws some message which should not be like

```

 ------ --------------------------------------------------------------------------------
  Line   modules/user/src/Nova/AddressResource.php
 ------ --------------------------------------------------------------------------------
  36     Call to an undefined method Illuminate\Database\Eloquent\Model::getDataJson().
 ------ --------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------
  Line   modules/user/src/Nova/UserResource.php
 ------ ---------------------------------------------------------------------------------------
  91     Call to an undefined method Themsaid\CashierTool\CashierResourceTool::onlyOnDetail().
 ------ ---------------------------------------------------------------------------------------

 ------ --------------------------------------------------------------------------------------------------------
  Line   modules/user/src/Http/Controllers/AddressesController.php
 ------ --------------------------------------------------------------------------------------------------------
  13     Call to an undefined method Illuminate\Contracts\Auth\Factory|Illuminate\Contracts\Auth\Guard::user().
  20     Call to an undefined method Illuminate\Contracts\Auth\Factory|Illuminate\Contracts\Auth\Guard::user().
  21     Call to an undefined method Illuminate\Contracts\Auth\Factory|Illuminate\Contracts\Auth\Guard::user().
 ------ --------------------------------------------------------------------------------------------------------
```

Although packages etc are correctly working. 

Is it my issue or this package :)

Thank it may be dumb question but i am first time using it.

**Comment by imansugirman** [comment]
Same Issue

**Comment by canvural** [comment]
I'm not sure what do you think is the error here. Those are errors that Larastan found. Which is expected. That's what this tool is for.

**Comment by vintagesucks** [comment]
@canvural Hi! I subscribed to this issue because I have the same problem. I agree that the original issue if not very clear, but also believe this still needs to be fixed.

---

> Although packages etc are correctly working.

To clarify, I believe this is supposed to mean that even though larastan reports undefined methods, the code in question runs without any problem as the method is in fact defined (elsewhere).

---

Example: I use [laravel-money](https://github.com/cknow/laravel-money) in a project. Simplified excerpt:

```php
<?php

namespace App\Rules;

use Cknow\Money\Money;
use Illuminate\Contracts\Validation\Rule;

class Euro implements Rule
{
    public function passes($attribute, $value)
    {
        try {
            Money::parseByIntlLocalizedDecimal($value, 'EUR')->getAmount();
        } catch (\Throwable $th) {
            return false;
        }

        return true;
    }
```

Larastan reports: `Call to an undefined method Cknow\Money\Money::getAmount()`

Technically this is correct. `Cknow\Money\Money::getAmount()` does not exist. The method comes from https://github.com/moneyphp/money, the package `laravel-money` wraps. 

I had to add `'#Call to an undefined method Cknow\\Money\\Money::getAmount()#'` to my `phpstan.neon` file under `ignoreErrors` to get rid of the error but I think I should not have to do this.

I'd be happy to put together a simple example repository to reproduce this, if you are interested.

**Comment by canvural** [comment]
> To clarify, I believe this is supposed to mean that even though larastan reports undefined methods, the code in question runs without any problem as the method is in fact defined (elsewhere).

Yes, that is expected from a static analysis. That piece of code could not be supported yet, or there is an error on your part. And phpstan/larastan will give an error.

> Larastan reports: `Call to an undefined method Cknow\Money\Money::getAmount()`
> 
> Technically this is correct. `Cknow\Money\Money::getAmount()` does not exist. The method comes from https://github.com/moneyphp/money, the package `laravel-money` wraps.
> 
> I had to add `'#Call to an undefined method Cknow\\Money\\Money::getAmount()#'` to my `phpstan.neon` file under `ignoreErrors` to get rid of the error but I think I should not have to do this.
> 
> I'd be happy to put together a simple example repository to reproduce this, if you are interested.

This error is not related to Laravel. You should ask the creator of that package to write a PHPStan extension for his package. Or [there is](https://github.com/JohnstonCode/phpstan-moneyphp) an unofficial PHPStan extension for `moneyphp` package. You can try to use that.

**Comment by vintagesucks** [comment]
@canvural That makes sense, thank you!
