### ISSUE TITLE
{relation}_count attribute may return null

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#1672]
- Larastan Version: 2.6.3
- `--level` used: 5

### Description

Currently we are sure [`{relation}_count` attribute](https://laravel.com/docs/10.x/eloquent-relationships#counting-related-models) is an integer.

https://github.com/nunomaduro/larastan/blob/73e5be5f5c732212ce6ca77ffd2753a136f36a23/src/Properties/ModelRelationsExtension.php#L73-L75

In the framework it may be null.

QueriesRelationships.php:L602-683
Eloquent/Collection.php:L100-106

Could we make it nullable?

This is where Larastan told me it is an int, and later failed with a fatal error.
(Laravel Nova field)

```diff
-            Number::make(__('Players'), static function (Model $model): ?int {
+            Number::make(__('Players'), static function (Model $model): int {
                 return $model->players_count;
             }),
```

**Comment by canvural** [comment]
Hi,

The `relation_count` is not actually nullable. I think it returns null because it's not loaded. You'd need to do `withCount('players')` in the query to be able to use `players_count`. 

But because this is near impossible to detect just with SA, we decided to make `relation_count` to be always available.

**Comment by szepeviktor** [comment]
Thank you for the guidance.
