### ISSUE TITLE
Can I hide Cannot access property  error when refering dynamic model field ?

### ISSUE THREAD

**Issue by sergeynilov** [nunomaduro/larastan#1804]
On laravel 10 app with nunomaduro/larastan 2.7.0 I got error :

`     Cannot access property $video_url on Illuminate\Database\Eloquent\Model|int|string.
`
on line : 

`        $videoUrls = $this->record->video_url;
`
Wonder are there some optiuons not to raise this error ?
It seems too tough...

**Comment by szepeviktor** [comment]
Make sure in code that `$this->record` is not an integer nor a string.

**Comment by sergeynilov** [comment]
Sorry, I did not understand. Sure, in my code $this->record  is an object. Do you mean to avoid this error I have :
1) use getAtribute( ...
OR
2) Use code like  :
```
if(is_object($this->record)) {
       $videoUrls = $this->record->video_url;
}

```
No other way ?

**Comment by szepeviktor** [comment]
I always ask this simple question: _What makes sure that X is of type Y?_

**Comment by sergeynilov** [comment]
Declaring type of a var I asuppose. $this->record is declared somewhere deeply in laravel/filament libraries. I use this var as I inherete some libraries. Not sure how can I rediclare it in my script ?

**Comment by calebdw** [comment]
You can't access properties on `Illuminate\Database\Eloquent\Model` because the base model does not have a backing table / migrations for Larastan to understand what properties actually exist.

There are several ways to solve this problem, but the best methods will usually solve the problem at the source instead of littering your codebase with `@var` declarations everywhere this is used.

If the model should be a specific model (like `Video`) then you need to narrow the type to only Video models---you can do this by overriding the class or creating a stub file for the library.

However, I'm assuming that because this is from a library then it might be trying to be model agnostic---in this case you can't access properties on the model and you have to use the public api (so `getAttribute`).

**Comment by canvural** [comment]
Hi,

We can't help further without more code examples.

If you don't want to get these kind of errors try using a lower PHPStan level or use the baseline feature.
