### ISSUE TITLE
Support firstWhere on a collection

### ISSUE THREAD

**Issue by alexis-riot** [nunomaduro/larastan#1832]
- Larastan Version: 2.8.1
- `--level` used: 5

### Description
Actually, LaraStan doesn't support the method `firstWhere()` on a collection, it return this kind of error:
> Match arm comparison between array|null and 'nps' is always false.

### Laravel code where the issue was found

```php
$kpi = $options->firstWhere('name', '=', 'kpi')?->value; // kpi is not an array.

$benchmarking = match ($kpi) {
    'nps' => new Nps(), // Match arm comparison between array|null and 'nps' is always false.
    ...
};
```

**Comment by mad-briller** [comment]
larastan has no special handling of the `firstWhere` method of collections, because laravel has defined templates for the collections itself:

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Collections/Traits/EnumeratesValues.php#L296

it's hard to say what your issue is with such a small amount of code, if you could elaborate further we may be able to help you better
such as what is `$options` a collection of ? where is the `->value` property defined, and what is it defined as?

**Comment by alexis-riot** [comment]
I've updated my code to :
```php
data_get($options->firstWhere('name', '=', 'kpi'), 'value');
```

With this method it doesn't throw any error from Larastan, but you're right, in his declaration Laravel his returning a `TValue` instead of a real value, look like a wrapper or something else.

Just to inform you on that issue, but on my side it has been solved by using data_get() helper.

**Comment by mad-briller** [comment]
`TValue` will be a [template type](https://phpstan.org/blog/generics-in-php-using-phpdocs) of the `Collection<TKey, TValue>`, so whatever your collection contains seems to have a `->value` property that is defined to be `array|null`

`data_get` isn't solving your issue, but is instead hiding it because `data_get` is [defined](https://github.com/laravel/framework/blob/9448e01699d43761e8bcf3d2ff53d0e3efb37432/src/Illuminate/Collections/helpers.php#L38-L46) to return `mixed` which level 5 wont report as an issue

**Comment by calebdw** [comment]
Where is the generic type defined for your collection? What is it?

**Comment by canvural** [comment]
Closing as it's solved.
