### ISSUE TITLE
Request to become a Larastan Maintainer

### ISSUE THREAD

**Issue by calebdw** [nunomaduro/larastan#1912]
Hello @canvural, @nunomaduro, and @szepeviktor!

I hope life has been treating y'all well. I've been contributing to Larastan for about a year now with a substantial uptick in contributions since the beginning of the year. During this period, I've had the opportunity to submit several bug fixes and new features, resolve issues, and assist others with the problems they are facing. I have been the biggest advocate for static analysis at my company and have a vested interest in the success of this project. I currently have 14 open PRs that will close as many issues, many of which are required for us to reach PHPStan level 3.

I completely understand and respect that everyone has varying commitments, which affects the time available to dedicate to this project. Unfortunately, it seems that lately Larastan has not been able to receive the attention it needs. For example, I have a PR (#1878) to support Laravel 11 since it was released a month ago that has not yet been merged despite significant community interest. Seeing this, I feel motivated to offer more substantial support.

Given my familiarity with the project and active engagement in recent updates and discussions, I am interested in officially supporting the project as a maintainer. I believe I can provide valuable assistance in managing PRs / issues, developing new features, and in ensuring that Larastan keeps pace with ongoing community needs.

Thank you for your consideration, and I look forward to the possibility of contributing more significantly to this project we all care about.

Best,

Caleb

**Comment by canvural** [comment]
Hi,

First of all thank you for your contributions!  Your dedication and contributions to the project over the past year have not gone unnoticed. They are really appreciated.

I've been maintaining Larastan for almost 5 years now. It has been a journey filled with highs and lows over the past five years. Through it all, I've managed to navigate the challenges and keep the project moving forward. Your willingness to step up and offer additional support is appreciated.

> Unfortunately, it seems that lately Larastan has not been able to receive the attention it needs.

That is true. It's because I was on holiday for some time and had other stuff to take care of. And I think that's perfectly normal in the open source world.

Selecting a collaborator for Larastan, or any open source project in that matter, is a decision that requires careful consideration. It's essential that we share the same vision, goals, and mindset for the project. While I really appreciate your interest in becoming more involved with Larastan, right now I'm not looking to expand the team. But please know that doesn't take away from how much I value your contributions. I'm excited to keep seeing your PRs,  even if it's not in an official capacity.

Edit: I know I am not the best with written communication. If you want to chat about this, I am up for it also!

**Comment by calebdw** [comment]
@canvural, thanks for the response!

> Through it all, I've managed to navigate the challenges and keep the project moving forward.

Thanks for all your work on this amazing project! I know it's not always easy to try and support all the "magic" that Laravel has to offer when it comes to static analysis.

> That is true. It's because I was on holiday for some time and had other stuff to take care of. And I think that's perfectly normal in the open source world.

Absolutely! The observation was in no way a slight against you, I understand that more important things come up---I just wanted to help take some of the load off your plate.

> Selecting a collaborator for Larastan, or any open source project in that matter, is a decision that requires careful consideration. It's essential that we share the same vision, goals, and mindset for the project. While I really appreciate your interest in becoming more involved with Larastan, right now I'm not looking to expand the team. But please know that doesn't take away from how much I value your contributions. I'm excited to keep seeing your PRs, even if it's not in an official capacity.

No worries! I completely understand :smile:---it's not something to be done lightly. I'll still keep sending PRs and helping out, but if I can ever do more just let me know!

> Edit: I know I am not the best with written communication. If you want to chat about this, I am up for it also!

I'm down for that :), chatting is much easier than written communication in my opinion.

**Comment by calebdw** [comment]
@nunomaduro, it was great meeting you at Laracon in Dallas last month! I enjoyed your talk on Pest v3 and am looking forward to updating and using all the new goodies.

We had discussed the possibility of me becoming a Larastan maintainer and mentioned you would talk to @canvural about it. I just wanted to follow up and see if you've had the chance to do that yet. As mentioned above, if y'all would like to chat about this in more detail with me, I would be more than happy to through whatever medium works best.

I would greatly appreciate the opportunity to contribute in a more official capacity and help propel Larastan to new heights.

Thanks!
