### ISSUE TITLE
Improve testing suite

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/larastan#226]
I would like to improve the testing suite having the same testing struture used like this: https://github.com/Roave/no-floaters/tree/master/tests/src.

**Comment by ondrejmirtes** [comment]
Are there any new rules in Larastan? Because that's what the link is about.

You should also look at how levels are tested, you can test various features like that (checking that some errors occur and some errors do not occur): https://github.com/phpstan/phpstan-strict-rules/tree/master/tests/Levels (you should test both, to see if the type inference works)

**Comment by nunomaduro** [comment]
I am fine with the current test suite.
