### ISSUE TITLE
Is a docker image planned?

### ISSUE THREAD

**Issue by Einenlum** [nunomaduro/larastan#285]
Is it planned at some point to have a docker image, as [phpstan does](https://github.com/phpstan/docker-image)?

**Comment by ondrejmirtes** [comment]
It does not make sense to be provided by 3rd party in this case. If you want Larastan inside Docker, inherit the PHPStan image and install Larastan inside it.

**Comment by szepeviktor** [comment]
Yes, that seems to be easy https://github.com/phpstan/docker-image/blob/master/Dockerfile#L39

**Comment by szepeviktor** [comment]
```dockerfile
FROM phpstan/phpstan

RUN composer global require nunomaduro/larastan
```

No! It is not that easy as Larastan needs to be inside your Laravel project!

**Comment by ondrejmirtes** [comment]
You can mount it as a volume.

**Comment by szepeviktor** [comment]
Larastan does not start without a Laravel project.

https://github.com/nunomaduro/larastan/blob/master/composer.json#L47-L52

There is no PHAR distribution of Larastan.

**Comment by deleugpn** [comment]
I just hit this one, it's quite a bummer. I'm trying to run larastan on a project from outside the project itself. The goal is to gain velocity. If I run it from inside the project itself, I need to wait for the entire project Docker to build (which takes longer).
Larastan doesn't seem to work as a standalone project at all.

**Comment by canvural** [comment]
Hi @deleugpn 

How are you running it? Did you mount your project as a volume inside the docker? Did you check the PHPStan [docs](https://github.com/phpstan/phpstan#install-phpstan-extensions) about Docker?

**Comment by deleugpn** [comment]
@canvural I tried the phpstan Docker solution by running

```
docker run --rm -v $(pwd):/app phpstan/phpstan analyse
```

but I get the following error:

```
[05:10 AM]-[root@docker]-[/home/customergauge/analytics-api]-[git larastan]
# docker run --rm -v $(pwd):/app phpstan/phpstan analyse
Note: Using configuration file /app/phpstan.neon.
Bootstrap file /composer/vendor/phpstan/phpstan/../../nunomaduro/larastan/bootstrap.php does not exist.
```

------------------------------------------------------------------------------------------------

I also tried running from a complete clean folder the following: 

```
composer require nunomaduro/larastan
./vendor/bin/phpstan analyse -c /path/to/project/phpstan.neon
```

But I get an error saying 

```
[15-Jan-2020 10:14:36 UTC] PHP Fatal error:  Trait 'Orchestra\Testbench\Concerns\CreatesApplication' not found in /tmp/larastan/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 26
Fatal error: Trait 'Orchestra\Testbench\Concerns\CreatesApplication' not found in /tmp/larastan/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 26
/tmp/larastan #
```

Now if I try to install Orchestra Testbench, I get composer conflicts. 


------------------------------------------------
So I then tried another approach: 

```
composer require laravel/framework
composer require orchestra/testbench
composer require nunomaduro/larastan
```

And then when I run `./vendor/bin/phpstan analyse -c /path/to/project/phpstan.neon` I get an error saying `undefined index: autoload`. This is because PHPStan is loading the `composer.json` file and looking for `autoload` key information, which a complete clean project like this does not have.

**Comment by canvural** [comment]
> Bootstrap file /composer/vendor/phpstan/phpstan/../../nunomaduro/larastan/bootstrap.php does not exist.

I think this error is because your vendor folder is under `/app/vendor` not `/composer/vendor` And this is expected.

PHPStan recommends installing extensions as global, using a custom Dockerfile. Please read [here](https://github.com/phpstan/phpstan#install-phpstan-extensions), and try that. I think that'll solve the issue.

**Comment by deleugpn** [comment]
I dug the problem to the `extension.neon` file in Larastan using the root directory. #416 fixed the issue for me.

**Comment by ondrejmirtes** [comment]
I’ve posted some suggestions in #416 that also tell us we don’t need to change anything in Larastan.
