### ISSUE TITLE
Static method App\MyModel::select() invoked with 2 parameters, 0-1 required.

### ISSUE THREAD

**Issue by larsnystrom** [nunomaduro/larastan#372]
- Larastan Version: 0.4.3
- `--level` used: 5

### Description

Using `select()` (https://laravel.com/docs/6.x/queries#selects) on an Eloquent model to select > 1 column triggers false positive "invoked with X parameters, 0-1 required". `select()` is variadic and can accept any number of arguments.

### Laravel code where the issue was found

```php
MyModel::select('firstcol', 'secondcol')->get();
```

**Comment by jefhar** [comment]
This issue appears to be fixed in #354.

I came here because of this issue. Upon some examination, I ran `composer require --dev "nunomaduro/larastan:dev-master#7cfe77d as 0.4.4-alpha"` to get the variadic parameter update, and larastan is happy with my model's `select()` method.

I don't know if it will auto-update to the next release, but I set a watch to be notified of the next release.

**Comment by canvural** [comment]
This is fixed in 0.5
