### ISSUE TITLE
Return type of find and findOrFail

### ISSUE THREAD

**Issue by xendk** [nunomaduro/larastan#379]
- Larastan Version: master 7cfe77d96e0686b3ac6f20a022b4511783abf921
- `--level` used: max

### Description

Getting a lot of errors on property access/method calls on models loaded with `find` or `findOrFail`. The issue is that the functions return a single model object or a collection if given multiple ids, but PHPStan doesn't know the difference, so it errors as the collection doesn't support the property/method.

I suspect more of Eloquents methods could have the same problem.

### Laravel code where the issue was found

```php
        $batch = Batch::findOrFail($batchId);
        $snapshot = $batch->snapshot;
```

Which gives me the error:

> Access to an undefined property Appocular\Assessor\Models\Batch|(Illuminate\Database\Eloquent\Collection&iterable<Appocular\Assessor\Models\Batch>)::$snapshot.

It is fixable with @var comments, but 

```php
        /** @var \Appocular\Assessor\Models\Batch $batch */
        $batch = Batch::findOrFail($batchId);
```

seems a tad verbose. Seems a bit counter productive that what one saves in code by using Eloquents nice API one needs to add in with @var comments to appease PHPStan.

Any chance Larastan could make PHPStan a bit wiser on the issue?

**Comment by szepeviktor** [comment]
Thank you for your report.

We have/had a lot of fain/OrFail problems.
e.g. https://github.com/nunomaduro/larastan/issues/187
Could you look into them?

**Comment by canvural** [comment]
What is the type of `$batchId`? Are you sure it's integer?

**Comment by xendk** [comment]
@canvural string actually, controller argument. But that should be fine with the Builder.

But you're on to something, changing the argument to `42` makes the error go away, and come back with `"42"`. But neither `(int) "42"` nor `intval("42")` makes it happy?

**Comment by canvural** [comment]
You have to pass an integer, for Larastan to understand that it should return single result.

But we can improve this. We can treat anything other than array to return a single model.

**Comment by nunomaduro** [comment]
Good idea @canvural - to be even better: other than an `iterable`.

**Comment by canvural** [comment]
Done in #400

**Comment by BonnieSawe** [comment]
@canvural is right  $batch = Batch::findOrFail((int) $batchId); works perfectly

**Comment by dillingham** [comment]
@canvural what if the value comes from the request?

@BonnieSawe I would hope to not have to clutter up my code with `(int)` anytime I pass a parameter

THe default and overall intentional behavior for find is find 1

**Comment by canvural** [comment]
@dillingham You can typehint your $args param with `array{id: int} ` and any other possible keys. Then PHPStan would understand `$args['id'] ` is integer type.

**Comment by dillingham** [comment]
@canvural thanks!  That works for one parameter nicely. It kind of breaks down if more complex, having to define every type in the dockblock for example. Like cases with multiple and from the request for example.

Is there any way to default find and findOrFail to being int unless otherwise? 
I would assume anyone trying to pass untyped arrays would have to do the work around.
Not the the default usage and expected usage. Its such a common method, would be awesome to not have to use work arounds

**Comment by canvural** [comment]
@dillingham  The whole point of using static analysis is to catch bugs by analyzing types. So I don't understand your complain.

Also, you'll get `Call to an undefined method App\Event|Illuminate\Database\Eloquent\Collection<App\Event>::duplicate(). ` this error only in level 7. If you want that strict analysis, you need to provide the correct types. If not, you can happily stay at level 6, or ignore these levels.

>  there are also cases where find() will be a string if the primary key is a uuid for example

That would also work. We don't make a special case just for `int`. 

[This](https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/ModelFindExtension.php) extension checks if the argument is iterable. If it is, return type would be a collection. Otherwise, we return either the model as return type, or the actual return type of the method if the argument is mixed type.

**Comment by canvural** [comment]
The point is to protect you from bugs for example if someone passes an array inside of `$args['id']` Then `$event->duplicate();` would not work because `$event` would be a collection, not model.

**Comment by dillingham** [comment]
@canvural not really a complaint just was a little confused. I am new to static analysis 

Just seemed to make a false alarm for something common, but that's the level I chose! :)

The level suggestion makes sense, I appreciate you taking the time and for maintaining this package!
