### ISSUE TITLE
Does Lumen have an internal error?

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#429]
or are we unable to understand Lumen's code?

(recently in CI)
```
 ------ ---------------------------------------------- 

  Line   Providers/AuthServiceProvider.php             

 ------ ---------------------------------------------- 

  33     Offset 'auth' does not exist on               

         Illuminate\Contracts\Foundation\Application.  

 ------ ---------------------------------------------- 
```

https://github.com/laravel/lumen/blob/master/app/Providers/AuthServiceProvider.php#L33

**Comment by szepeviktor** [comment]
4 years old commit!

**Comment by canvural** [comment]
No, the error is not in Lumen. Something recently changed in PHPStan. In 0.12.8 or 0.12.7 and causes this issue.

Funny thing is the same code doesn't produce an error in Laravel. Only in Lumen.

**Comment by canvural** [comment]
Ok, I can reproduce the error now. I don't know why I couldn't before.

The thing is, `\Illuminate\Contracts\Foundation\Application` does not implement `ArrayAccess`, the implementation does (`Illuminate\Foundation\Application`). That's why we have [all this](https://github.com/nunomaduro/larastan/blob/master/src/Analyser/Scope.php#L44-L116).

This is still working. Our `getTypeFromArrayDimFetch` implementation returns the correct type for the array access, but the `NonexistentOffsetInArrayDimFetchRule` rule started to complain now.

As far as I know, there is no way to `lie` about an interface implements the `ArrayAccess` to PHPStan. I tried stubs, didn't work. So, I don't know what can we do more. @ondrejmirtes any ideas?

**Comment by ondrejmirtes** [comment]
I'm not sure if the `$type` [here](https://github.com/nunomaduro/larastan/blob/master/src/Analyser/Scope.php#L47) is about `Illuminate\Contracts\Foundation\Application` or something else?

If it's about the Application class then besides overriding `isOffsetAccessible`, you should also override `hasOffsetValueType` and `getOffsetValueType` to persuade PHPStan in `NonexistentOffsetInArrayDimFetchRule`.
