### ISSUE TITLE
Absolute paths to configuration etc. files

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/larastan#47]
Please notify users that files must have absolute path.

E.g. `-c, --configuration=CONFIGURATION  Path to project configuration file` could be `-c, --configuration=CONFIGURATION  Absolute path to project configuration file`

Also for autoload-file.

**Comment by nunomaduro** [comment]
Hey @szepeviktor 👋

Those options aren't documented yet. Shouldn't we ignore/remove them from the command CodeAnalyseCommand forcing people to use PHPStan like normal on those cases?

I need some time to think about this.

Thanks for creating this issue! ☺️

**Comment by szepeviktor** [comment]
Hello 👋 

Setting a configuration file pulls the plug on Larastan as `extension.neon` will be ignored.

**Comment by mfn** [comment]
> Those options aren't documented yet.

It's documented now, at least via the Command; but it doesn't state the requirement about absolute paths:
```
Options:
  -c, --configuration=CONFIGURATION  Path to project configuration file [default: "/vagrant/project/vendor/nunomaduro/larastan/src/Console/../../extension.neon"]
```
I stumbled across this too.

In my case:
- I'm already using phpstan
- I already have a `phpstan.neon` in the root of the project

I would have expected either of the two things:
- `./artisan code:analyse` would pick up the mine automatically
  or
- `./artisan code:analyse --configuration=phpstan.neon`

But neither does (nowhere it's started the first does, just a tale of experience here).

I would like to see the file resolution being improved so that picks up relative files from the CWD where `./artisan` is ran; I think that's sensible.

**Comment by szepeviktor** [comment]
I usually use `./artisan code:analyse --configuration=$(pwd)/phpstan.neon`

**Comment by mfn** [comment]
Yeah, I know, it's totally fixable. But in the hopes of unsurprising DX I wrote this ;-)

**Comment by johanvanhelden** [comment]
This PR should more or less address this issue. The config file will show it is an absolute path.

https://github.com/nunomaduro/larastan/pull/178/files

**Comment by nunomaduro** [comment]
This issue seems no longer be relevant.
