### ISSUE TITLE
Incorrect return type when accessing model's relationship property when using IDE helper

### ISSUE THREAD

**Issue by mr-feek** [nunomaduro/larastan#476]
- Larastan Version: `dev-master`
- `--level` used: 5

### Description
When running larastan on a model file that has laravel-ide-helper docblocks committed, we run into errant generic return type issues.

### Laravel code where the issue was found

Here is a test case added to `Tests\Features\Models\Relations.php`

```php
/** @test */
    public function test_it_fails_with_ide_helper(): ?Account
    {
        $user = new User();

        return $user->accounts->first();
    }
```

This test passes, until docblocks generated by laravel-ide-helper are added to the `User.php` model.

```
/**
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Account[] $accounts
 */
```

```
./vendor/bin/phpstan analyse -c ./tests/phpstan-tests.neon --ansi --memory-limit=1G tests/Features/Models/Relations.php
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------------------------------------------------------------
  Line   Relations.php
 ------ ------------------------------------------------------------------------------------------------------------
  149    Method Tests\Features\Models\Relations::test_it_fails_with_ide_helper() should return App\Account|null but
         returns Illuminate\Database\Eloquent\Model|null.
```

### Notes
This test case will pass if we typehint the collection being returned to be `@property-read \Illuminate\Database\Eloquent\Collection<\App\Account>|\App\Account[] $accounts`

Is there a way we can infer this automatically? Laravel-ide-helper is quite a common tool for most laravel developers.

### Workaround
use `@var` annotation

```php
/** @test */
    public function test_it_fails_with_ide_helper(): ?Account
    {
        $user = new User();
        
        /** @var \App\Account $account */
        $account = $user->accounts->first();
        return $account
    }
```

**Comment by ondrejmirtes** [comment]
From: https://github.com/phpstan/phpstan/issues/3020#issuecomment-591116328

I'd rather solve the underlyting issue rather than come up with some hacks. Larastan makes the Collection generic (https://github.com/nunomaduro/larastan/blob/master/stubs/Collection.stub) so the correct way to write this is:

```
@property-read \Illuminate\Database\Eloquent\Collection<int, \App\Account> $accounts
```

I guess you can't use laravel-ide-helper to generate your code for you. Since this is about 1st party code (your own), you can easily fix that by writing an annotation that PHPStan understands.

**Comment by mr-feek** [comment]
I think we should still keep this open on the larastan end, as it is probably an issue a lot of us will have using both of these tools

**Comment by canvural** [comment]
I think this could be solved by `phpstan-property` when https://github.com/phpstan/phpstan/issues/2976 is implemented.

**Comment by ondrejmirtes** [comment]
I have a solution for you. The problem is not with "property" per se, but with the `Collection|Foo[]` part, which can occur in other PHPDoc tags as well.

You could write a simple TypeNodeResolverExtension (meant for overriding PHPDoc type interpretation) that interprets Eloquent's `Collection|Foo[]` as `Collection<int, Foo>`, fixing this issue and making it quite intuitive. This is how this extension looks like, but for Doctrine collection (I've written this at my dayjob):

https://gist.github.com/ondrejmirtes/56af016d0595788d5400b8dfb6520adc

**Comment by ondrejmirtes** [comment]
Arguably, this should become part of Larastan.

**Comment by canvural** [comment]
That's cool! Yeah we can implement that.

Same logic can be applied to other phpdocs larave-ide-helper generates I guess. For example `@method static \Illuminate\Database\Eloquent\Builder|\App\Models\User newModelQuery()` should be interpreted as `Builder<\App\Models\User>`

**Comment by ondrejmirtes** [comment]
Yes :) Feel free to ask if you have any problems.

**Comment by mr-feek** [comment]
Fantastic @ondrejmirtes , thanks so much for the suggestion!

I'd love to take a shot at this
