### ISSUE TITLE
Call to undefined method PHPStan\Type\MixedType::getClassName()

### ISSUE THREAD

**Issue by oprypkhantc** [nunomaduro/larastan#512]
- Larastan Version: 0.5.4
- `--level` used: 1

### Description

The following error happens:
```
   Error 

  Call to undefined method PHPStan\Type\MixedType::getClassName()

  at vendor/nunomaduro/larastan/src/ReturnTypes/BuilderModelFindExtension.php:77
    73|         $model = $methodReflection->getDeclaringClass()->getActiveTemplateTypeMap()->getType('TModelClass');
    74|         $returnType = $methodReflection->getVariants()[0]->getReturnType();
    75|         $argType = $scope->getType($methodCall->args[0]->value);
    76| 
  > 77|         $returnType = ModelTypeHelper::replaceStaticTypeWithModel($returnType, $model->getClassName());
    78| 
    79|         if ($argType->isIterable()->yes()) {
    80|             if (in_array(Collection::class, $returnType->getReferencedClasses(), true)) {
    81|                 $genericCollectionReturnType = new GenericObjectType(Collection::class, [$model]);
```

### Laravel code where the issue was found

```php
$feedback = new Feedback();

return $feedback->with('tags.info')->findOrFail($feedbackId);
```
or
```php
return (new Feedback())->query()->with('tags.info')->findOrFail($feedbackId);
```

**Comment by canvural** [comment]
Hi,

This is fixed in 0.5.5 Please update and try again.

**Comment by oprypkhantc** [comment]
Hi @canvural.

Yep, the issue has indeed been resolved. Thank you!

**Comment by canvural** [comment]
Actually your code example discovers another potential bug or an edge case. In your case, Larastan doesn't know that `findOrFail` returns an instance of `Feedback` But if you do `Feedback::query` or `Feedback::with` it would. Cause both `with` and `query` is static methods on the model and shouldn't be called as instance methods.

It is really an edge case rather than a bug maybe. I've never seen the usage of `(new Model)->query()->...` So you should use `with` and `query` statically wherever you can if you want better type inference from Larastan.

**Comment by oprypkhantc** [comment]
Am aware. It's all 2015 legacy :(

But we also had the same problem in places where queries were created with a scope, like this:
```php
TransactionRecurringAutopay::active()
```
which have also been resolved, so the fix still makes sense even for projects without legacy code.
