### ISSUE TITLE
Eloquent Collection map method does not always has model as first parameter of its callback

### ISSUE THREAD

**Issue by canvural** [nunomaduro/larastan#550]
- Larastan Version: 0.5.7
- `--level` used: max

### Description

Given the following code:
```php
/**
 * @param EloquentCollection<User> $collection
 */
public function testMapPartition(EloquentCollection $collection): SupportCollection
{
    return $collection->partition(function (User $user) {
        return $user->accounts()->count() > 1;
    })->map(function (EloquentCollection $users) {
        return $users->count();
    });
}
```

Larastan gives this error:
```
Parameter #1 $callback of method  lluminate\Database\Eloquent\Collection<App\User>::map() expects callable(App\User, int): mixed, Closure(Illuminate\Database\Eloquent\Collection): mixed given.
```

Did not test but this might also apply to other methods than `partition`

**Comment by Daanra** [comment]
I think we might have to remove the ` @template TModel of Model` annotation
 from the `EloquentCollection.stub` file altogether.

Collection methods like `partition` and `groupBy` return a `EloquentCollection<EloquentCollection<TModelClass>>`, so that would be considered invalid.

We might want to treat `EloquentCollection`s the same way we treat the regular SupportCollection class and allow the EloquentCollection to enumerate over any type of value. E.g.:
```php
/**
 * @template TValue
 * @extends \Illuminate\Support\Collection<int, TValue>
 */
class Collection extends \Illuminate\Support\Collection
{
}
```

**Comment by canvural** [comment]
@Daanra Yeah, we might have to do that. Logically `Eloquent Collection` should hold just model instances, that's why I added the `TModel of Model`
