### ISSUE TITLE
Bug with autoloading on phpstan 0.12.22

### ISSUE THREAD

**Issue by zlodes** [nunomaduro/larastan#559]
- Larastan Version: 0.5.7
- PhpStan Version: 0.12.22
- `--level` used: max

### Description
For latest version of phpstan (0.12.22)!

On analyze action:
```php
 ErrorException thrown in /builds/trv3/core/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 109 while loading bootstrap file /builds/trv3/core/vendor/phpstan/phpstan/../../nunomaduro/larastan/bootstrap.php: Undefined index: AI\Core\
```

Method ApplicationResolver@getProjectSearchDirs has wrong composer dir:

Expected: `/home/vagrant/projects/core/vendor/composer`
Actual: `phar:///home/vagrant/projects/ai/core/vendor/phpstan/phpstan/phpstan/vendor/composer`

phpstan code reference: https://github.com/phpstan/phpstan-src/commit/a1d3990c95b7a064a0451111153a6bef39f5d9a2

**Comment by szepeviktor** [comment]
Thank you for your report.

**Comment by atabixalex** [comment]
We're experiencing the same problem.

**Comment by canvural** [comment]
Yep, Larastan's own tests are also failing for the same reason.

You can use PHPStan 0.12.21 until we fix the issue.

**Comment by learn2draw** [comment]
PHPStan 0.12.21 gives the same error for me, using 0.12.20 however works

**Comment by nunomaduro** [comment]
cc @ondrejmirtes.

**Comment by canvural** [comment]
Looks like the issue is here: https://github.com/nunomaduro/larastan/blob/master/src/ApplicationResolver.php#L102-L104

When we request `ClassLoader` via reflection looks like it gets the `vendor/phpstan/phpstan/phpstan/vendor/composer/ClassLoader.php` file. Not the `vendor/composer/ClassLoader.php`

Right now I don't have the time to look deeper. Just a pointer if anyone wants to attempt a fix.

**Comment by nunomaduro** [comment]
The function https://www.php.net/manual/en/function.realpath.php may help to solve this.

**Comment by ondrejmirtes** [comment]
Can you explain what the code in https://github.com/nunomaduro/larastan/blob/master/src/ApplicationResolver.php does and why are you inspecting the PSR4 maps?

I'm quite sure you could ask PHPStan for `%composerAutoloaderProjectPaths%` instead and discover autoloaders that way. It might return up to three autoloader paths I think.

**Comment by nunomaduro** [comment]
I have installed a fresh Laravel application with Larastan. And it works. Can someone explaining me how can I reproduce the issue?

**Comment by ondrejmirtes** [comment]
Well it’s true that the ClassLoader inside PHAR gets loaded as the first one now so the behaviour others are seeing in this issue is expected...

**Comment by canvural** [comment]
When I tried to run Larastans tests with `composer test` it was failing for the same reason as in the original issue.

**Comment by nunomaduro** [comment]
Got it. Give me a second.

**Comment by canvural** [comment]
> Can you explain what the code in [/src/ApplicationResolver.php@`master`](https://github.com/nunomaduro/larastan/blob/master/src/ApplicationResolver.php) [](/nunomaduro/larastan/blob/HEAD@{2020-05-04T16:42:42Z}/src/ApplicationResolver.php) does and why are you inspecting the PSR4 maps?
> 
> I'm quite sure you could ask PHPStan for `%composerAutoloaderProjectPaths%` instead and discover autoloaders that way. It might return up to three autoloader paths I think.

In that class, we are trying to find all the [service provider](https://laravel.com/docs/7.x/providers)s that the application uses. And register them to the Laravel app.

**Comment by nunomaduro** [comment]
I am a little bit tired today, maybe someone on the community would like to jump in: https://twitter.com/enunomaduro/status/1257399917691224067.

**Comment by ondrejmirtes** [comment]
Something along these lines will probably be sufficient: https://github.com/nunomaduro/larastan/pull/561

You don't even need my suggestion with `%composerAutoloaderProjectPaths%` because I noticed that you're getting `composer.json` from the current working directory anyway, so there's no need for reflection to tell us the path to the Composer class loader...

**Comment by mobyface** [comment]
> I am a little bit tired today, maybe someone on the community would like to jump in: https://twitter.com/enunomaduro/status/1257400309212680197.

The problem is related to the ApplicationResolver class which is only used in a package environment and not in a Laravel Application environment (see bootstrap.php file). The first autoload.psr-4 namespace (first key) is read from the composer.json in order to resolve all project classes. The method getProjectSearchDirs is intent to obtain the relative directory with source code (in my case ./src).

I think the solution is maybe a lot simpler because the source code directory is also in the composer.json file, namely the corresponding value within autoload.psr-4. 

Finally, some points which might be relevant:

1.  I wonder why only the first item from autoload.psr-4 is read from composer.json. There could be multiple items here right?

2.  It might be a good moment to reflect on the relation with the 'paths' parameter in the phpstan.neon file. In my case this also points to the ./src directory.

3. The main task of the ApplicationResolver is to register al the serviceproviders. These might also be found in the composer.json -> extra.laravel.providers.

**Comment by ondrejmirtes** [comment]
https://github.com/nunomaduro/larastan/pull/561 fixes this issue.

@SocyList I just restored how it previously worked before I changed the order of autoloaders in PHPStan itself. Of course we could take a deeper look at the code but it's not necessary now.

**Comment by Panoptik** [comment]
Faced with this issue.
Fixed by requiring laravel framework with composer

`composer req --dev laravel/framework`

without laravel it show mentioned error with unknown key

**Comment by szepeviktor** [comment]
Could you tell us about your project that uses Larastan but nit Laravel?

**Comment by Panoptik** [comment]
I worked with lot of laravel projects. As well I write some small composer packages for these projects. 
Sometimes I explicitly require laravel as dev dependency for package. My last attempt was not required to install laravel, but I tried to configure larastan as usual with `composer req nunomaduro/larastan` and it started to run but hungs with mentioned error

As well I would mention that orchestra/testbench-dusk package also required and it is minimal to have it together with laravel for start using larastan.
Probably these packages should be configured as dependencies for larastan, but up to you.

I left my comment just to help somebody else faced with this issue
