### ISSUE TITLE
Calling `array_flatten` on Collection

### ISSUE THREAD

**Issue by brendt** [nunomaduro/larastan#92]
Not sure what the right solution is here.

```php
array_flatten($this->app['docs.navigation'])
```

The value of `$this->app['docs.navigation']` is a `Collection`, and `array_flatten` works with it, I suppose because `Collection` is an `Iterable`. This is marked as an error though:

```php
Parameter #1 $array of function array_flatten expects array, Illuminate\Support\Collection|null given.
```

I know I can call `flatten` on the `Collection`, though I'm not a 100% sure the config will always return a `Collection`.. 

Like I said, this might not be something that this package has to fix, but I'd like your input nevertheless.

**Comment by nunomaduro** [comment]
Hey @brendt! I think the problem is not the Collection. The problem is that you **may** resolve `null` from `$this->app['docs.navigation']`.

Do you mind of updating your code to:

```
array_flatten($this->app['docs.navigation'] ?? []);
```

And tell me the result. ☺️

**Comment by brendt** [comment]
```php
array_flatten($this->app['docs.navigation'] ?? [])
```

Actually fixes the issue! It's a rather smart thing, PHPStan. 👌@ondrejmirtes

**Comment by brendt** [comment]
I thought so too 😅

Here you go https://github.com/illuminate/support/blob/master/Arr.php#L207

**Comment by ondrejmirtes** [comment]
You actually haven't fixed the problem, just postponed it to level 6. (Because before, the answer was always wrong - you have Collection and trying to pass it to array.) Right now, you have `Collection|array` which is partly right and that gets reported on level 6.

The correct fix ofcourse is to add `Collection` to the phpDoc in the function source code (send a PR to  `illuminate/support`).
